# Generated by Django 5.2.7 on 2025-12-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosegreso',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.producto'),
        ),
    ]
